"""Report table  migration.

Revision ID: 7cca2a3cbf8e
Revises: 4f89b8ca008a
Create Date: 2025-11-30 13:46:02.975015

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.types import Text
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7cca2a3cbf8e'
down_revision = '4f89b8ca008a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.add_column(sa.Column('agent_name', sa.String(length=500), nullable=False))
        batch_op.add_column(sa.Column('publication_date', sa.String(50), nullable=True))
        batch_op.add_column(sa.Column('article_type', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('analysis_payload', postgresql.JSONB(astext_type=Text()), nullable=True))
        batch_op.alter_column('title',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.Text(),
               existing_nullable=False)
        batch_op.alter_column('created_at',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
        batch_op.create_index(batch_op.f('ix_reports_agent_name'), ['agent_name'], unique=False)
        batch_op.drop_column('analysis')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.add_column(sa.Column('analysis', sa.TEXT(), nullable=True))
        batch_op.drop_index(batch_op.f('ix_reports_agent_name'))
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.TIMESTAMP(),
               existing_nullable=False)
        batch_op.alter_column('title',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=500),
               existing_nullable=False)
        batch_op.drop_column('analysis_payload')
        batch_op.drop_column('article_type')
        batch_op.drop_column('publication_date')
        batch_op.drop_column('agent_name')

    # ### end Alembic commands ###
