"""Initial migration.

Revision ID: 7e7f9faf336b
Revises: 
Create Date: 2025-11-26 21:13:32.035041

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e7f9faf336b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('site_name', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('analysis', sa.Text(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('risk_level', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('url')
    )
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reports_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_reports_site_name'), ['site_name'], unique=False)

    op.create_table('website_fetch',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('site_name', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('url')
    )
    with op.batch_alter_table('website_fetch', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_website_fetch_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_website_fetch_site_name'), ['site_name'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('website_fetch', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_website_fetch_site_name'))
        batch_op.drop_index(batch_op.f('ix_website_fetch_id'))

    op.drop_table('website_fetch')
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reports_site_name'))
        batch_op.drop_index(batch_op.f('ix_reports_id'))

    op.drop_table('reports')
    # ### end Alembic commands ###
