name: CI

on:
  push:
    branches: [dev, main]
  pull_request:
    branches: [dev, main]


jobs:
  backend:
    name: Backend - Flask
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: cybermag/backend
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Lint with flake8
        run: flake8 .

      - name: Run backend tests with pytest
        run: pytest

  frontend:
    name: Frontend - React
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: cybermag/frontend
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18.19.0'

      - name: Install dependencies
        run: npm ci

      - name: Run React tests with npm
        run: npm test -- --watchAll=false